### ISSUE TITLE
Error when creating cluster w/o TLS

### ISSUE THREAD

**Issue by hferentschik** [jenkins-x/terraform-aws-eks-jx#14]
Using the minimal configuration, just specifying _vault_user_, I get  the following error when trying to use the resulting `jx-requirements.yaml` (cluster creation was ok):

```
error: overwriting the default requirements: loading requirements from file "/tmp/terraform/jx-requirements.yml": validation failures in YAML file /tmp/terraform/jx-requirements.yml:
ingress.tls.email: Invalid type. Expected: string, given: null
ingress.domain: Invalid type. Expected: string, given: null
```

**Comment by hferentschik** [comment]
The generated jx-requirements.yaml looks like this:

```yaml
autoUpdate:
  enabled: false
  schedule: ""
terraform: true
cluster:
  clusterName: tf-jx-regular-spaniel
  environmentGitOwner: ""
  environmentGitPublic: true
  provider: eks
  region: us-east-1
gitops: true
environments:
  - key: dev
  - key: staging
  - key: production
ingress:
  domain:
  ignoreLoadBalancer: true
  externalDNS: false
  tls:
    email:
    enabled: false
    production: false
kaniko: true
secretStorage: vault
vault:
  aws:
    iamUserName: cjxd-vault
    dynamoDBTable: vault-unseal-tf-jx-regular-spaniel-random19210290120
    dynamoDBRegion: us-east-1
    kmsKeyId: aa295a8f-3845-45bd-8f7b-e8bb8e39428c
    kmsRegion: us-east-1
    s3Bucket: vault-unseal-tf-jx-regular-spaniel-20200330150302388000000004
    s3Region: us-east-1
storage:
  logs:
    enabled: true
    url: s3://logs-tf-jx-regular-spaniel-20200330150303736700000008
  reports:
    enabled: true
    url: s3://reports-tf-jx-regular-spaniel-20200330150302388500000005
  repository:
    enabled: true
    url: s3://repository-tf-jx-regular-spaniel-20200330150302390300000007
versionStream:
  ref: master
  url: https://github.com/jenkins-x/jenkins-x-versions.git
webhook: prow
```
