### ISSUE TITLE
jx-requirements.yml.tpl doesn't reflect changes for storage key in Jenkins X v3

### ISSUE THREAD

**Issue by polasekr** [jenkins-x/terraform-aws-eks-jx#232]
### Summary 
Storage key in the template is object, while Jenkins X v3 requires it to be an array. When jx-requirement.yml file generated by the template while storage is enabled, following jx-requirement.yml file is rendered

```
  logs:
    enabled: true
    url: s3://s3bucket
  reports:
    enabled: true
    url: s3://s3bucket
  repository:
    enabled: true
    url: s3://s3bucket
```
Jenkins X throws following error:

```
Error: failed to load requirements in dir .: failed to unmarshal YAML file /home/robert/src/stjude/jx3-config/jx-requirements.yml due to error unmarshaling JSON: while decoding JSON: json: cannot unmarshal object into Go struct field RequirementsConfig.spec.storage of type []v4beta1.StorageConfig
```

### Steps to reproduce the behavior
Build jenkins x v3 with storage enabled

### Expected behavior
jx-requirement.yml suppose to be in the following format:

```
...
  storage:
  - name: logs
    url: gs://logs-tf-jx-gentle-titmouse-1603d78dd9a2
  - name: reports
    url: gs://reports-tf-jx-gentle-titmouse-1603d78dd9a2
  - name: repository
    url: gs://repository-tf-jx-gentle-titmouse-1603d78dd9a2
```
as per https://github.com/jenkins-x/jx3-eagle/blob/master/jx-requirements.yml

### Terraform version
n/a
The output of `terraform version` is:

n/a

### Module version

n/a

### Operating system

n/a
